// <auto-generated />
namespace GalaxyForge.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class GalaxyDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GalaxyDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202302231800312_GalaxyDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
