namespace GalaxyForge.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class galaxyDB : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Events", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.Governments", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.Organizations", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.Species", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.Structures", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.EventCelestialBodies", "CelestialBody_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.GovernmentCelestialBodies", "CelestialBody_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Structures", "CelestialBodyId_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Equipments", "CelestialBodyId_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Organizations", "CelestialBody_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Species", "CelestialBodyId", "dbo.CelestialBodies");
            DropForeignKey("dbo.Cities", "CelestialBodyId_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Ships", "CelestialBodyId_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.EventCelestialBodies", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.StructureEvents", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.SectorEvents", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.Governments", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.Organizations", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.Species", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.GovernmentCelestialBodies", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.GalacticZoneGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.Equipments", "GovernmentId_Id", "dbo.Governments");
            DropForeignKey("dbo.StructureGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.SolarSystemGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.SectorGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.RegionGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.GalacticSectorGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.Ships", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.Events", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.GalacticZones", "GalacticSectorId_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.GalacticSectorGovernments", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.Organizations", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.Species", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.Structures", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.Governments", "Organization_Id", "dbo.Organizations");
            DropForeignKey("dbo.Species", "OrganizationId", "dbo.Organizations");
            DropForeignKey("dbo.Equipments", "OrganizationId_Id", "dbo.Organizations");
            DropForeignKey("dbo.StructureOrganizations", "Organization_Id", "dbo.Organizations");
            DropForeignKey("dbo.Ships", "Organization_Id", "dbo.Organizations");
            DropForeignKey("dbo.Equipments", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.StructureEvents", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.StructureGovernments", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.StructureOrganizations", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.Species", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.CelestialBodies", "SolarSystemId", "dbo.SolarSystems");
            DropForeignKey("dbo.Events", "SolarSystem_Id", "dbo.SolarSystems");
            DropForeignKey("dbo.SolarSystemGovernments", "SolarSystem_Id", "dbo.SolarSystems");
            DropForeignKey("dbo.Organizations", "SolarSystem_Id", "dbo.SolarSystems");
            DropForeignKey("dbo.Species", "SolarSystem_Id", "dbo.SolarSystems");
            DropForeignKey("dbo.Structures", "SolarSystem_Id", "dbo.SolarSystems");
            DropPrimaryKey("dbo.Cities");
            DropPrimaryKey("dbo.CelestialBodies");
            DropPrimaryKey("dbo.Events");
            DropPrimaryKey("dbo.Governments");
            DropPrimaryKey("dbo.GalacticSectors");
            DropPrimaryKey("dbo.Organizations");
            DropPrimaryKey("dbo.Species");
            DropPrimaryKey("dbo.Structures");
            DropPrimaryKey("dbo.Equipments");
            DropPrimaryKey("dbo.SolarSystems");
            DropPrimaryKey("dbo.Ships");
            AlterColumn("dbo.Cities", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.CelestialBodies", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Events", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Governments", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.GalacticSectors", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.GalacticSectors", "Q", c => c.Int());
            AlterColumn("dbo.GalacticSectors", "R", c => c.Int());
            AlterColumn("dbo.GalacticSectors", "S", c => c.Int());
            AlterColumn("dbo.GalacticZones", "Q", c => c.Int());
            AlterColumn("dbo.GalacticZones", "R", c => c.Int());
            AlterColumn("dbo.GalacticZones", "S", c => c.Int());
            AlterColumn("dbo.Organizations", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Species", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Structures", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.Equipments", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.SolarSystems", "Id", c => c.Int(nullable: false));
            AlterColumn("dbo.SolarSystems", "Q", c => c.Int());
            AlterColumn("dbo.SolarSystems", "R", c => c.Int());
            AlterColumn("dbo.SolarSystems", "S", c => c.Int());
            AlterColumn("dbo.Sectors", "Q", c => c.Int());
            AlterColumn("dbo.Sectors", "R", c => c.Int());
            AlterColumn("dbo.Sectors", "S", c => c.Int());
            AlterColumn("dbo.Regions", "Q", c => c.Int());
            AlterColumn("dbo.Regions", "R", c => c.Int());
            AlterColumn("dbo.Regions", "S", c => c.Int());
            AlterColumn("dbo.Ships", "Id", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Cities", "Id");
            AddPrimaryKey("dbo.CelestialBodies", "Id");
            AddPrimaryKey("dbo.Events", "Id");
            AddPrimaryKey("dbo.Governments", "Id");
            AddPrimaryKey("dbo.GalacticSectors", "Id");
            AddPrimaryKey("dbo.Organizations", "Id");
            AddPrimaryKey("dbo.Species", "Id");
            AddPrimaryKey("dbo.Structures", "Id");
            AddPrimaryKey("dbo.Equipments", "Id");
            AddPrimaryKey("dbo.SolarSystems", "Id");
            AddPrimaryKey("dbo.Ships", "Id");
            AddForeignKey("dbo.Events", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.Governments", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.Organizations", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.Species", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.Structures", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.EventCelestialBodies", "CelestialBody_Id", "dbo.CelestialBodies", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GovernmentCelestialBodies", "CelestialBody_Id", "dbo.CelestialBodies", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Structures", "CelestialBodyId_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Equipments", "CelestialBodyId_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Organizations", "CelestialBody_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Species", "CelestialBodyId", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Cities", "CelestialBodyId_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Ships", "CelestialBodyId_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.EventCelestialBodies", "Event_Id", "dbo.Events", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StructureEvents", "Event_Id", "dbo.Events", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SectorEvents", "Event_Id", "dbo.Events", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Governments", "Event_Id", "dbo.Events", "Id");
            AddForeignKey("dbo.Organizations", "Event_Id", "dbo.Events", "Id");
            AddForeignKey("dbo.Species", "Event_Id", "dbo.Events", "Id");
            AddForeignKey("dbo.GovernmentCelestialBodies", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GalacticZoneGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Equipments", "GovernmentId_Id", "dbo.Governments", "Id");
            AddForeignKey("dbo.StructureGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SolarSystemGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SectorGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RegionGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GalacticSectorGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Ships", "Government_Id", "dbo.Governments", "Id");
            AddForeignKey("dbo.Events", "GalacticSector_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.GalacticZones", "GalacticSectorId_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.GalacticSectorGovernments", "GalacticSector_Id", "dbo.GalacticSectors", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Organizations", "GalacticSector_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.Species", "GalacticSector_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.Structures", "GalacticSector_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.Governments", "Organization_Id", "dbo.Organizations", "Id");
            AddForeignKey("dbo.Species", "OrganizationId", "dbo.Organizations", "Id");
            AddForeignKey("dbo.Equipments", "OrganizationId_Id", "dbo.Organizations", "Id");
            AddForeignKey("dbo.StructureOrganizations", "Organization_Id", "dbo.Organizations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Ships", "Organization_Id", "dbo.Organizations", "Id");
            AddForeignKey("dbo.Equipments", "Structure_Id", "dbo.Structures", "Id");
            AddForeignKey("dbo.StructureEvents", "Structure_Id", "dbo.Structures", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StructureGovernments", "Structure_Id", "dbo.Structures", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StructureOrganizations", "Structure_Id", "dbo.Structures", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Species", "Structure_Id", "dbo.Structures", "Id");
            AddForeignKey("dbo.CelestialBodies", "SolarSystemId", "dbo.SolarSystems", "Id");
            AddForeignKey("dbo.Events", "SolarSystem_Id", "dbo.SolarSystems", "Id");
            AddForeignKey("dbo.SolarSystemGovernments", "SolarSystem_Id", "dbo.SolarSystems", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Organizations", "SolarSystem_Id", "dbo.SolarSystems", "Id");
            AddForeignKey("dbo.Species", "SolarSystem_Id", "dbo.SolarSystems", "Id");
            AddForeignKey("dbo.Structures", "SolarSystem_Id", "dbo.SolarSystems", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Structures", "SolarSystem_Id", "dbo.SolarSystems");
            DropForeignKey("dbo.Species", "SolarSystem_Id", "dbo.SolarSystems");
            DropForeignKey("dbo.Organizations", "SolarSystem_Id", "dbo.SolarSystems");
            DropForeignKey("dbo.SolarSystemGovernments", "SolarSystem_Id", "dbo.SolarSystems");
            DropForeignKey("dbo.Events", "SolarSystem_Id", "dbo.SolarSystems");
            DropForeignKey("dbo.CelestialBodies", "SolarSystemId", "dbo.SolarSystems");
            DropForeignKey("dbo.Species", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.StructureOrganizations", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.StructureGovernments", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.StructureEvents", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.Equipments", "Structure_Id", "dbo.Structures");
            DropForeignKey("dbo.Ships", "Organization_Id", "dbo.Organizations");
            DropForeignKey("dbo.StructureOrganizations", "Organization_Id", "dbo.Organizations");
            DropForeignKey("dbo.Equipments", "OrganizationId_Id", "dbo.Organizations");
            DropForeignKey("dbo.Species", "OrganizationId", "dbo.Organizations");
            DropForeignKey("dbo.Governments", "Organization_Id", "dbo.Organizations");
            DropForeignKey("dbo.Structures", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.Species", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.Organizations", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.GalacticSectorGovernments", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.GalacticZones", "GalacticSectorId_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.Events", "GalacticSector_Id", "dbo.GalacticSectors");
            DropForeignKey("dbo.Ships", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.GalacticSectorGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.RegionGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.SectorGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.SolarSystemGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.StructureGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.Equipments", "GovernmentId_Id", "dbo.Governments");
            DropForeignKey("dbo.GalacticZoneGovernments", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.GovernmentCelestialBodies", "Government_Id", "dbo.Governments");
            DropForeignKey("dbo.Species", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.Organizations", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.Governments", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.SectorEvents", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.StructureEvents", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.EventCelestialBodies", "Event_Id", "dbo.Events");
            DropForeignKey("dbo.Ships", "CelestialBodyId_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Cities", "CelestialBodyId_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Species", "CelestialBodyId", "dbo.CelestialBodies");
            DropForeignKey("dbo.Organizations", "CelestialBody_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Equipments", "CelestialBodyId_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Structures", "CelestialBodyId_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.GovernmentCelestialBodies", "CelestialBody_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.EventCelestialBodies", "CelestialBody_Id", "dbo.CelestialBodies");
            DropForeignKey("dbo.Structures", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.Species", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.Organizations", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.Governments", "City_Id", "dbo.Cities");
            DropForeignKey("dbo.Events", "City_Id", "dbo.Cities");
            DropPrimaryKey("dbo.Ships");
            DropPrimaryKey("dbo.SolarSystems");
            DropPrimaryKey("dbo.Equipments");
            DropPrimaryKey("dbo.Structures");
            DropPrimaryKey("dbo.Species");
            DropPrimaryKey("dbo.Organizations");
            DropPrimaryKey("dbo.GalacticSectors");
            DropPrimaryKey("dbo.Governments");
            DropPrimaryKey("dbo.Events");
            DropPrimaryKey("dbo.CelestialBodies");
            DropPrimaryKey("dbo.Cities");
            AlterColumn("dbo.Ships", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Regions", "S", c => c.Int(nullable: false));
            AlterColumn("dbo.Regions", "R", c => c.Int(nullable: false));
            AlterColumn("dbo.Regions", "Q", c => c.Int(nullable: false));
            AlterColumn("dbo.Sectors", "S", c => c.Int(nullable: false));
            AlterColumn("dbo.Sectors", "R", c => c.Int(nullable: false));
            AlterColumn("dbo.Sectors", "Q", c => c.Int(nullable: false));
            AlterColumn("dbo.SolarSystems", "S", c => c.Int(nullable: false));
            AlterColumn("dbo.SolarSystems", "R", c => c.Int(nullable: false));
            AlterColumn("dbo.SolarSystems", "Q", c => c.Int(nullable: false));
            AlterColumn("dbo.SolarSystems", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Equipments", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Structures", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Species", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Organizations", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.GalacticZones", "S", c => c.Int(nullable: false));
            AlterColumn("dbo.GalacticZones", "R", c => c.Int(nullable: false));
            AlterColumn("dbo.GalacticZones", "Q", c => c.Int(nullable: false));
            AlterColumn("dbo.GalacticSectors", "S", c => c.Int(nullable: false));
            AlterColumn("dbo.GalacticSectors", "R", c => c.Int(nullable: false));
            AlterColumn("dbo.GalacticSectors", "Q", c => c.Int(nullable: false));
            AlterColumn("dbo.GalacticSectors", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Governments", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Events", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.CelestialBodies", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Cities", "Id", c => c.Int(nullable: false, identity: true));
            AddPrimaryKey("dbo.Ships", "Id");
            AddPrimaryKey("dbo.SolarSystems", "Id");
            AddPrimaryKey("dbo.Equipments", "Id");
            AddPrimaryKey("dbo.Structures", "Id");
            AddPrimaryKey("dbo.Species", "Id");
            AddPrimaryKey("dbo.Organizations", "Id");
            AddPrimaryKey("dbo.GalacticSectors", "Id");
            AddPrimaryKey("dbo.Governments", "Id");
            AddPrimaryKey("dbo.Events", "Id");
            AddPrimaryKey("dbo.CelestialBodies", "Id");
            AddPrimaryKey("dbo.Cities", "Id");
            AddForeignKey("dbo.Structures", "SolarSystem_Id", "dbo.SolarSystems", "Id");
            AddForeignKey("dbo.Species", "SolarSystem_Id", "dbo.SolarSystems", "Id");
            AddForeignKey("dbo.Organizations", "SolarSystem_Id", "dbo.SolarSystems", "Id");
            AddForeignKey("dbo.SolarSystemGovernments", "SolarSystem_Id", "dbo.SolarSystems", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Events", "SolarSystem_Id", "dbo.SolarSystems", "Id");
            AddForeignKey("dbo.CelestialBodies", "SolarSystemId", "dbo.SolarSystems", "Id");
            AddForeignKey("dbo.Species", "Structure_Id", "dbo.Structures", "Id");
            AddForeignKey("dbo.StructureOrganizations", "Structure_Id", "dbo.Structures", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StructureGovernments", "Structure_Id", "dbo.Structures", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StructureEvents", "Structure_Id", "dbo.Structures", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Equipments", "Structure_Id", "dbo.Structures", "Id");
            AddForeignKey("dbo.Ships", "Organization_Id", "dbo.Organizations", "Id");
            AddForeignKey("dbo.StructureOrganizations", "Organization_Id", "dbo.Organizations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Equipments", "OrganizationId_Id", "dbo.Organizations", "Id");
            AddForeignKey("dbo.Species", "OrganizationId", "dbo.Organizations", "Id");
            AddForeignKey("dbo.Governments", "Organization_Id", "dbo.Organizations", "Id");
            AddForeignKey("dbo.Structures", "GalacticSector_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.Species", "GalacticSector_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.Organizations", "GalacticSector_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.GalacticSectorGovernments", "GalacticSector_Id", "dbo.GalacticSectors", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GalacticZones", "GalacticSectorId_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.Events", "GalacticSector_Id", "dbo.GalacticSectors", "Id");
            AddForeignKey("dbo.Ships", "Government_Id", "dbo.Governments", "Id");
            AddForeignKey("dbo.GalacticSectorGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.RegionGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SectorGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.SolarSystemGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StructureGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Equipments", "GovernmentId_Id", "dbo.Governments", "Id");
            AddForeignKey("dbo.GalacticZoneGovernments", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.GovernmentCelestialBodies", "Government_Id", "dbo.Governments", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Species", "Event_Id", "dbo.Events", "Id");
            AddForeignKey("dbo.Organizations", "Event_Id", "dbo.Events", "Id");
            AddForeignKey("dbo.Governments", "Event_Id", "dbo.Events", "Id");
            AddForeignKey("dbo.SectorEvents", "Event_Id", "dbo.Events", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StructureEvents", "Event_Id", "dbo.Events", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EventCelestialBodies", "Event_Id", "dbo.Events", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Ships", "CelestialBodyId_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Cities", "CelestialBodyId_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Species", "CelestialBodyId", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Organizations", "CelestialBody_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Equipments", "CelestialBodyId_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.Structures", "CelestialBodyId_Id", "dbo.CelestialBodies", "Id");
            AddForeignKey("dbo.GovernmentCelestialBodies", "CelestialBody_Id", "dbo.CelestialBodies", "Id", cascadeDelete: true);
            AddForeignKey("dbo.EventCelestialBodies", "CelestialBody_Id", "dbo.CelestialBodies", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Structures", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.Species", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.Organizations", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.Governments", "City_Id", "dbo.Cities", "Id");
            AddForeignKey("dbo.Events", "City_Id", "dbo.Cities", "Id");
        }
    }
}
